name: Laravel CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1' # Update this line to use PHP 8.1

    - name: Update dependencies
      run: composer update --prefer-dist --no-progress --no-suggest

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Copy environment file
      run: cp .env.example .env

    - name: Generate application key
      run: php artisan key:generate

    - name: Run tests
      run: vendor/bin/phpunit

    - name: Check coding standards
      run: vendor/bin/phpcs

    - name: Check static analysis
      run: vendor/bin/phpstan analyze

    - name: Check security vulnerabilities
      run: composer exec security-checker security:check

    - name: Install Node.js and npm
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install JavaScript dependencies
      run: npm install

    - name: Run mix (Laravel Mix)
      run: npm run production

    - name: Clean up
      run: php artisan optimize:clear
